### ISSUE TITLE
Prüfschritt 9.1.4.1  Ohne Farben nutzbar

### ISSUE THREAD

**Issue by MarcHaunschild** [BIK-BITV/BIK-Web-Test#216]
In den Erläuterungen wird als Beispiel für eine mögliche Hervorhebung das "Fetten" von Links genannt.
Mir reicht das eigentlich nicht, denn Links können sich ja in wichtigem Text befinden, der bereits fett ist. Auch lassen sich Links dann generell nicht von "wichtigem Text" unterscheiden.
Daher schlage ich vor, die Fettung von Text nicht als Unterscheidungsmerkmal zu nennen.

**Comment by sweckenmann** [comment]
Es geht ja um "zusätzliche" Hervorhebungen. Dürfte es nicht klar sein, dass fette Schrift in einem Absatz mit Schrift in fetter Darstellung keine "zusätzliche" Hervorhebung ist? 
Umgekehrt ein Link mit fetter Darstellung in einem Fließtext mit nicht fetter Schrift kann man nach meiner Ansicht nicht mit einem fail bestrafen, weil es eine zusätzliche Hervorhebung ist.

**Comment by MarcHaunschild** [comment]
In der WCAG heißt es dazu ja "Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.." - und die Information war meiner Meinung nach "ich bin ein Link" bzw die mögliche Aktion zu einer anderen Ressource wechseln zu können mit einer Aktion (Klick).
Wenn ein fetter Text wichtig oder ein Link oder noch etwas anderes sein kann (und man nur an unterschiedlichen Farben die eigentliche Bedeutung erkennen kann), war mir das bisher immer zu wenig. Denn dann steht die Hervorhebung ja für "vielleicht bin ich ein Link, vielleicht aber auch ein wichtiger Text oder noch etwas drittes"
Bin ich da wirklich zu streng?
Es heißt in der WCAG dann ja auch weiter "The intent of this Success Criterion is to ensure that all users can access information that is conveyed by color differences, that is, by the use of color where each color has a meaning assigned to it."
Und das ist typischerweise bei Links ja der Fall. Bei vielen Webseiten sind Links in Texten mit einer Farbe passend zum CD hervorgehoben. Andere farbliche Hervorhebungen sind oft rot für Fehlermeldungen, gelb für Warnungen und grün für Erfolgsmeldungen.
Alle vier sind oft zusätzlich fett (was auch Sinn macht, sogar wenn sie mit strong ausgezeichnet sind, weil ich meine, dass Meldungen und Warnungen durchaus wichtiger Text sind) - zusammen mit einfach nur wichtigem Text hat man dann insgesamt 5 verschiedene Arten von Text, die fett sein können. Und da kommt das ins Spiel: "that is, by the use of color where each color has a meaning assigned to it". Typischerweise haben Webseiten ja eben Link, Warnung, Erfolg u.a.m. mit **eindeutigen** Farben markiert, für die man dann aber auch Farben erkennen muss, weil zusätzliche Merkmale (alle fett) sie untereinander nicht unterscheidbar machen und die Intention des SC (eine bestimmte Information auch ohne Farbe zu transportieren) nicht mehr gewährleistet ist.
Es ist diese Eindeutigkeit, die in dem "each color has a meaning" steckt, die nicht transportiert wird.

**Comment by stefanFarnetani** [comment]
@MarcHaunschild Ich kann deinen Einwand gut nachvollziehen. 

Ich würde aber bold, italic usw. nicht per se verbieten. In meinen Augen ist der wichtige Aspekte die Unterscheidung zum umliegenden Text. Das muss im Zweifelsfall im Kontext beurteilt werden. Ist also ein Text fett, dann reicht eine Auszeichnung des Links im gleichen Schnitt nicht aus. Ich sage gleicher Schnitt weil es mittlerweile mehr als nur bold und regular auch im Web gibt. Wird bold=600 verwendet und der Link dann wiederum in extrabold 800 gesetzt (und sind die Schnitte visuell klar zu unterscheidbar), dann geht auch bold > extrabold.

Wir fordern kein einheitliches Styleguide. Der Link muss nicht in allen Texten gleich ausgezeichnet sein. Das ist wünschenswert aber nicht zwingend. Der Link kann also in einer Meldung anders ausgezeichnet sein als im Fließtext. Es muss nur unterscheidbar sein (Nutzende sind lernfähig innerhalb eines Systems!) und ohne große Hindernisse nutzbar sein. 
Das ist in meinen Augen die Anforderung der WCAG; ein Mindeststandard. Anmerkung und freiwillig mehr fordern finde ich gut. Aber ein fail kann ich nicht aussprechen, auch wenn ich das manchmal wollen würde..

Auch die Technique [F73: Failure of Success Criterion 1.4.1 due to creating links that are not visually evident without color vision](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F73) beschreibt in ihrer Testprozedur, dass bold und italic und auch genügend Farbkontrast zum Fließtext ausreichend sind.

P.S. Das Beispiel mit der Meldung müsste man sich im konkreten Fall anschauen. Erkennbarkeit einer Meldung sollte ja nicht alleine auf der Fettung basieren; es gibt eine Positionierung, Weißraum, evtl. einen Rahmen oder Icon und nicht zuletzt der Textinhalt selbst. Ich will nur sensibilisieren für unterschiedliche grafische Herangehensweisen (die wir nie alle berücksichtigen können) und das wir uns da nicht zu stark in Prüfschritten festlegen dürfen.

.. nur meine Meinung.

**Comment by MarcHaunschild** [comment]
Vielen Dank für Eure Rückmeldungen! Werde das ab sofort genau wir ihr bewerten!

**Comment by johannesFischer84** [comment]
@MarcHaunschild 

Wenn es unklar ist, ob eine Fettung für eine Hervorhebung oder eine Link-Kennzeichnung steht (beide fett gestaltet), würde ich das wahrscheinlich nicht als zweites optisches Merkmal akzeptieren. Aber wenn Hervorhebungen optisch anders dargestellt werden als durch Fettung (oder anderen Fett-Schnitt wie Stefan erläutert hat), dann wäre die Fettung als optische Kennzeichnung eines Links wieder eindeutig und in Ordnung.

**Comment by MarcHaunschild** [comment]
Also geht es dir auch um Eindeutigkeit. Klar würde ich es auch akzeptieren wenn **nur** Links fett sind oder **nur** Links _kein_ Icon haben (wenn beispielsweise Warnungen ein Dreieck haben und Erfolgsmeldungen ein Häkchen und Infohinweise ein "i").

Hmm - jetzt sind wir zwei zu zwei...

**Comment by johannesFischer84** [comment]
Ich denke, man muss sich den jeweiligen Einzelfall ansehen.

**Comment by MarcHaunschild** [comment]
> Ich denke, man muss sich den jeweiligen Einzelfall ansehen.

Ja, das nehme ich so mit. Wenn ohne Farbe die Bedeutung verschiedener fetter Texte nicht mehr erkennbar ist, würde ich abwerten und vermutlich auch die Mehrheit der Prüfer. Der Hinweis von @sweckenmann, dass es sich ja um eine **zusätzliche** Auszeichnung handeln muss, geht ja in diese Richtung.
Also in dubio pro reo und aufgrund von Erfahrung letztlich eine Ermessensentscheidung treffen....

Vielen Dank euch allen!
