### ISSUE TITLE
Prüfschritt 11.1.3.4 Ausrichtung

### ISSUE THREAD

**Issue by michaelnissenbaum** [BIK-BITV/BIK-Web-Test#397]
Hallo zusammen,

ich habe eine Frage erhalten, die die klappbaren Android-Geräte betrifft. Wie sollen wir den Prüfschritt in Bezug auf klappbare Android-Geräte bewerten, da in diesem Fall kein herkömmlicher Querformatmodus existiert?

**Comment by MarcHaunschild** [comment]
Meine Meinung: so wie immer.
Es muss funktionieren egal wie herum man das Gerät hält.
Es kann ja sein, dass es fest vor einer Person montiert wird. Wenn man dann ein anderes Format hat, kann das zusätzliche Probleme verursachen, aber womöglich ist es aus anderen Gründen Nötig, das Gerät in einer bestimmten Ausrichtung zu montieren (z.B. Zugänglichkeit des Stromanschlusses von der Seite, die nach einem Schlaganfall nicht gelähmt ist).

In der intention des WCAG SC wird eine feste Befestigung auch explizit erwähnt:

Some users have their devices mounted in a fixed orientation (e.g. on the arm of a power wheelchair). Therefore, websites and applications need to support both orientations by not restricting the orientation. Changes in content or functionality due to the size of display are not covered by this criterion which is focused on restrictions of orientation.

**Comment by johannesFischer84** [comment]
Bei der Bewertung von Prüfschritten an Webseiten geht es nicht speziell um einzelne Geräte, da die Webseite möglichst auf allen möglichen Geräten/Browsern barrierefrei nutzbar sein soll. Falls auf dem Gerät/Browser aus irgendenem Grund kein Querformat möglich ist, muss man zur Prüfung von WCAG 1.3.4 ein anderes Gerät bzw. Browser heranziehen.

Übrigens ist 11.1.3.4 aus der EN 301 549 nur für Software relevant. Vielleicht gehört dieses Issue eigentlich zum App-Test und ist irrtümlich im Web-Test-Repository gelandet? Bei Apps wäre das Betriebsystem statt dem Browser die zugrunde liegende Plattform. Android ermöglicht im Allgemeinen das Querformat. Falls das spezielle Gerät dies nicht vorsieht, müsste man auch hier ein anderes Gerät zur Prüfung heranziehen. Android-Apps können auf verschiedensten Geräten installiert werden und überall soll die App so barrierefrei wie möglich funktionieren.

Fazit: WCAG 1.3.4 ist unabhängig vom Gerät immer zu prüfen.

**Comment by detlevhfischer** [comment]
@michaelnissenbaum Ich denke, auch in Fällen, wo das Display nach Aufklappen quadratisch ist und es also keinen anderen Umbruch gäbe, könnte es für Nutzende, die Geräte fest montieren (z.B. am Rolli), zwingende Gründe geben, eine bestimmte Ausrichtung zu nutzen, weil dann z.B. Tasten am Gerät besser oder überhaupt erst  erreichbar wären..

Können wir das Issue schließen?
